### ISSUE TITLE
Question re merging values when clustering

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-openrefine#1]
I got a bit confused with "merging values" in the lesson https://github.com/data-lessons/library-openrefine/blob/master/lesson-materials/Basic-OpenRefine-functions-I.md#clustering

Merging values doesn't mean it merges rows or records does it? It just allows you to "clean up" values which leads to cleaner facets? Just thinking, librarians will be worried about this so it might be worth stepping through an example in detail to illustrate what it is doing and not doing.

**Comment by weaverbel** [comment]
@ostephens - Any thoughts on this since you are the expert :-)

**Comment by ostephens** [comment]
Agree that "merge" is ambiguous but it is the term used in Refine so I think we are stuck with it.

 It is defined in the text on the first & second use the second defn being the clearer IMO: "'merging' the values together - that is replace with a single consistent value"

So it may make sense to use this defn throughout. Also agree an example might help although I think (hope) the exercises make it clear what is happening
