### ISSUE TITLE
Basic Functions II: Incorrect Challenge answer

### ISSUE THREAD

**Issue by ostephens** [data-lessons/library-openrefine#102]
The change to the order of the lesson has broken the Challenge currently labelled 'Exercise 2'. It has the Q:

Q: How many articles in the file don’t have a licence assigned?
A: 6

However, with the 'split multi-valued cells' exercise now in Basic Functions I, you cannot easily divine the answer to the number of non-licenced articles from this facet - as the facet count gives in rows not in records

**Comment by ostephens** [comment]
This also affects Exercise 3 in same episode

**Comment by ostephens** [comment]
Options I can see:
- Rethink order of lesson again
-  Change these exercises
- Get participants to reverse the Author/Subject split with the 'Merge multi-valued cells' function in Basic Functions I (could be the exercise in place of splitting subjects?) before doing this part of the lesson.

Think the last one is the most sensible - and possibly gives a good opportunity to highlight some of the shortcomings of the Records mode. However, we need to split the Authors to do the Clustering work in episode Basic Functions III

**Comment by ccronje** [comment]
@ostephens if you are happy with the new order, getting the learners to split and merge might be the way to go (perhaps merge with a different separator to add something new). I think to leave it split leading into the next episode will be too confusing. Then add the split again as step one of Clustering.

**Comment by ccronje** [comment]
But if you want to demo the 'cautions' around split and record mode you could append it to Ex. 2 or 3?

**Comment by ostephens** [comment]
@ccronje what do you think of the new order? 

I like that it gets to some 'meat' more quickly, and in terms of general principles introducing rows vs records earlier makes sense - it's just that Records get complicated quickly!

**Comment by ccronje** [comment]
@ostephens agree, it's grown on me already :smile:, and I think librarians like the Records mode, being database savvy. Plus it's a nice 'different to Excel' to highlight early.

**Comment by ostephens** [comment]
Another possibility - chance to demonstrate the Undo/Redo option early in the lesson?

**Comment by ccronje** [comment]
I don't mind Undo/Redo where it is because:

1. Provides a breather
2. Many steps have been performed by that point so clear demo

**Comment by ccronje** [comment]
And the Exporting data section that follows on from Undo/Redo demos the time-saving aspect nicely when you have a long list of processes captured.

**Comment by ostephens** [comment]
OK - will wait for @jt14den to comment but currently thinking:

* Leave the Split exercises in  Basic Functions I
* Do the Facet and expose the problem of being in Records mode
* Re-merge cells (Author and Subject)
* Look at facet again showing how it works

**Comment by ostephens** [comment]
Although just of Undo/Redo note that in the USU scratchpad yesterday the question of mentioning this earlier was brought up http://pad.software-carpentry.org/lc2017-usu

**Comment by ccronje** [comment]
@ostephens I added a comment wrt Undo/Redo above. In reference to your bullet points, learners would have to make sure they're in Records mode in order to spot the count issue. Being their first exposure to Facets it might be a bit too much to problem solve, but will be good to hear comments from @jt14den and others.

**Comment by ostephens** [comment]
Thanks @ccronje - yes I recognise the advantage of having a substantial list of steps to fully demonstrate Undo/Redo - that was my immediate reaction on seeing the suggestion yesterday so glad we had the same thought :)

They should already be in Records mode - as this is part of the previous episode. However, it won't matter if they are or not in terms of seeing the large number of items in the Facet which seem not to have a Licence

**Comment by ostephens** [comment]
Agreed that we'll fix this by teaching the 'join multi-valued cells' function in Episode 03. See #116

**Comment by ostephens** [comment]
Closing this as now under issue #111  and PR #116
