### ISSUE TITLE
Align objectives with learning outcome language in Bloom's 

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-openrefine#104]
See http://swcarpentry.github.io/instructor-training/19-lessons/ When development is done (great job!!), please edit learning outcomes so they fit the language in Bloom’s taxonomy. The most important think I learnt about this from Instructor Training is that we cannot use 'understand' as it isn't measurable.

**Comment by ostephens** [comment]
We already have an issues for this #66

Closing this in favour of #66
