### ISSUE TITLE
Rename lessons based on concepts covered to improve flow

### ISSUE THREAD

**Issue by Jabble** [data-lessons/library-openrefine#106]
I'm brand new to teaching and contributing to Library Carpentry, and find it difficult to know what is covered in a lesson without transparent naming (e.g. "Basic Functions" 1–5) and then recall which lesson includes what.

More informative lesson names can help learners, and contributors, get to know what will be covered in a particular lesson from the outset, and hone-in on the content they're interested in learning or contributing to.

I believe this will also help to clearly see the flow of lessons and what may need to be moved around, merged and split.

### basic-functions-I 
Could be "Working with Data in OpenRefine" with possible content:

- Getting to know Rows and and Records
- Getting to know Columns, Reordering and Renaming columns, sorting data (from basic-functions-IV)

### basic-functions-II 
Could be "Using Facets and Filters"

### basic-functions-III
Could be "Using Clustering"

### basic-functions-IV
Could be merged into basic-functions-I

### basic-functions-V
Could be split into "Common Transformations" and "Transformations with GREL", or more along the lines of  #15 

### advance-functions
Could be split into "Looking up data" (URL, Reconciliation, Cross function) and "Adding extensions" with more added as mentioned in #65

**Comment by ostephens** [comment]
Mainly +1 to this - but can we separate out the 'renaming' bit from the 'merge into' and 'split into' suggestions?

I'm 100% in favour of renaming - please go ahead  along the lines you've suggested.

The restructuring is a bigger challenge and just done a load of work on this to get to where we are right now. More needs doing but want to try to settle in the changes that have already been made before we do more work on this. See  #14 and #15 for existing issues relating to this

**Comment by jt14den** [comment]
+1 to renaming, but I agree with @ostephens on the restructuring bit and think we now have a decent sized episodes to work with.

**Comment by Jabble** [comment]
Great, and I agree with both of you about my issue. I read through some of the discussions about restructuring, but am not sure exactly where they're at. This was aimed more at making the point that renaming can help in thinking about the structure. I'll practice making my issues more discrete!

**Comment by ostephens** [comment]
Fixed by #112 
Discussions about structure will be dealt with under the relevant issues
