### ISSUE TITLE
Formatting consistency ('follow the instructor' versus 'exercise')

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-openrefine#127]
Some boxes that are labelled Exercises at the moment aren’t Exercises in the SWC sense. What would be a consistent way to distinguish between 'Follow the instructor' and an 'Exercise'? Which blockquote classes should we use? See http://swcarpentry.github.io/lesson-example/04-formatting/ for blockquote class styles.

Suggestions discussed on Gitter:

For 'Follow the instructor'
- use blockquote class 'checklist' (e.g. http://www.tim-dennis.com/libcarp-pitt-notes-exercises/03-basic-functions-I/)
- 'Follow the instructor' is not optional (i.e. will impact learner in later episodes if not followed)

For an 'Exercise'
- use blockquote class 'challenge'
- use blockquote class 'solution' within a challenge if needed (optional)
- an 'Exercise' is optional

Questions
1. Is using 'checklist' for 'Follow the instructor' misusing the SWC style?
2. Should we eliminate Exercise numbers?
3. Should Exercises be grouped at the bottom of each episode?

**Comment by ccronje** [comment]
Outcome from meeting http://pad.software-carpentry.org/post-lc2017 (OpenRefine Discussion Agenda):

Questions
1. Is using 'checklist' for 'Follow the instructor' misusing the SWC style?
No. We decided to use checklist formatting (e.g. http://www.tim-dennis.com/libcarp-pitt-notes-exercises/03-basic-functions-I/) for directions which participants can follow, and Exercises (blockquote class 'challenge') for proper exercises where participants are expected to work out an answer/approach for themselves. This may mean converting some of the existing text or exercises into checklists.

2. Should we eliminate Exercise numbers?
Yes (have created an issue to do this https://github.com/data-lessons/library-openrefine/issues/135).

3. Should Exercises be grouped at the bottom of each episode?
Need to ensure there are exercises for each part of the episode - exercises should be kept close to the relevant material, not necessarily at the bottom of the episode - and if people want to contribute to lessons, bottom of episode would be a good option to accommodate extra challenges. In future consider moving to a pattern of Instruction -> Worked Example -> Exercise , using the 'faded example' style e.g. http://data-lessons.github.io/library-shell/02-counting-mining/ - Count, sort and print.

**Comment by ccronje** [comment]
Not sure how to action Question 1. Maybe we could create an issue for each episode and assign? Then do the same once https://github.com/data-lessons/library-openrefine/issues/15 is completed.

**Comment by ostephens** [comment]
@ccronje I think an issue for each episode the best way to go.
I'd suggest that we do this across all current lessons - I think it would be better to do this for Episode 7 before we split it (because changing style doesn't need any discussion now, but the split is bound to take time and discussion)

**Comment by ccronje** [comment]
@ostephens good idea - if you can think of a good issue title I'll create the issues 👍

**Comment by ccronje** [comment]
Sorry I was feeling very lazy last night, I'll think of something ;-)

**Comment by ostephens** [comment]
@ccronje happy to pick this up - just trying to get a report written at the moment and haven't had a chance to look at anything else for the last 2 days. Hoping to surface tomorrow!

**Comment by ostephens** [comment]
OK - have added issues for each episode to re-format step-by-step episodes. I'm guessing that we'll need further review of each episode once this is done, but let's get these done first

**Comment by ccronje** [comment]
Thanks @ostephens! I plan to make a start end of next week (I'll assign myself to an issue when I do so you know)

**Comment by ccronje** [comment]
Hi @ostephens @jt14den I've made a start on this with PR https://github.com/data-lessons/library-openrefine/pull/154. I was having trouble previewing in Jekyll, and was wondering @jt14den if you have any advice on how to incorporate http://swcarpentry.github.io/lesson-example/05-checking/ into the workflow http://www.tim-dennis.com/swc/2016/07/25/contributing-carpentries.html? I'm a bit rusty with git and found reviewing your blog post very helpful thanks :-)
