### ISSUE TITLE
Add workaround in setup incase IT issues

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-openrefine#128]
Shall we add https://my.datascientistworkbench.com/ (a virtual lab which includes OpenRefine) to [Setup](http://data-lessons.github.io/library-openrefine/setup/)?

@weaverbel has tested the lesson with it and reported "Great response times, it all worked. Good option for workshops IMHO."

**Comment by ostephens** [comment]
I'm happy if it all works smoothly. Do we know which version of OR they run?

**Comment by ccronje** [comment]
@ostephens it's version 2.6-rc1

**Comment by ostephens** [comment]
Thanks @ccronje

**Comment by ccronje** [comment]
@ostephens @weaverbel (& others) do you think we should add this workaround? If yes, is it best placed in http://data-lessons.github.io/library-openrefine/setup/ or http://data-lessons.github.io/library-openrefine/guide/?

**Comment by weaverbel** [comment]
Happy for it to be added @ccronje with a caveat that it is not a service under our control so it might go away at some stage.

**Comment by ccronje** [comment]
Ok thanks @weaverbel, add it to the setup or guide?

**Comment by weaverbel** [comment]
Guide, I'd say - if it's in set up, we have a problem ;-) @ccronje

**Comment by ostephens** [comment]
+1 to adding to guide

**Comment by ccronje** [comment]
Ha yes, thanks @weaverbel @ostephens I've added it to https://github.com/data-lessons/library-openrefine/pull/134. Closing this now.
