### ISSUE TITLE
Maintaining the lesson

### ISSUE THREAD

**Issue by ostephens** [data-lessons/library-openrefine#13]
I am happy to volunteer to maintain this - anyone else willing?

**Comment by ccronje** [comment]
Happy to volunteer here as well

**Comment by weaverbel** [comment]
@ostephens @ccronje I've got a nice messy dataset on solar patents I scraped from IP Australia. Good candidate for data cleanup.I'll upload it into the data area when I get a chance.

**Comment by pitviper6** [comment]
I can step up as well to maintain. I want to improve my lesson on the anti-slavery petitions anyway!

**Comment by ccronje** [comment]
That'd great @pitviper6 - we've been talking on gitter about forking a separate repo for dh-openrefine to make it easier to manage the two streams. @weaverbel should the repo be part of the library team https://github.com/orgs/data-lessons/teams/library/repositories? Are you able to add @ostephens and @pitviper6 please?

**Comment by drjwbaker** [comment]
Has this happened?

**Comment by ccronje** [comment]
@drjwbaker I can't see a way to invite @ostephens and @pitviper6 with my permissions - I think 'team maintainer' role or higher can. Another way: Owen and Juliane might be able to see a 'request to join' on this page https://github.com/orgs/data-lessons/teams

**Comment by ostephens** [comment]
I think invitations have to be issued - I don't see a 'request to join' option

**Comment by pitviper6** [comment]
I can't fibnd a request to join eiither

**Comment by weaverbel** [comment]
Hi all - this needs to be done by @tracykteal - Tracy can you please add @ostephens and @pitviper6  as part of the library team https://github.com/orgs/data-lessons/teams/library/repositories ?
Thanks
Belinda

**Comment by tracykteal** [comment]
done!

**Comment by ostephens** [comment]
I now have access - thanks @tracykteal
Assuming this can be closed now
