### ISSUE TITLE
Instructor Notes

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-openrefine#130]
This lesson has no Instructor Notes http://data-lessons.github.io/library-openrefine/guide/. These are helpful for passing on tips to potential instructors. See http://data-lessons.github.io/library-data-intro/guide/ for an example of how this might be done.

Tips specific to Refine might relate to the difficulty of getting the text on the screen big enough for live demos and workarounds you've developed. Or that people sometimes download the files as a html page in error.

**Comment by ccronje** [comment]
Added comments to https://github.com/data-lessons/library-openrefine/pull/134. Closing this now thanks @drjwbaker.
