### ISSUE TITLE
Testing the lesson with OpenRefine v2.7

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-openrefine#132]
The lesson tests ok with the latest version https://github.com/OpenRefine/OpenRefine/releases/tag/2.7 up to and including the CrossRef API example (haven't had a chance to go beyond that).

There is an issue (not lesson-related) where it hangs doing a **regular expression** search using the **Text filter**. I've been able to reproduce it but would be good to get confirmation from others.

**Comment by ccronje** [comment]
Should we update http://data-lessons.github.io/library-openrefine/setup/?

**Comment by weaverbel** [comment]
Yes !  It doesn't mention needing Java Runtime Environment to work but that is a deal breaker - no Java, no OpenRefine.

**Comment by weaverbel** [comment]
Maybe punch up the JRE info or bold it a bit?

**Comment by ccronje** [comment]
Thanks @weaverbel I've updated setup https://github.com/data-lessons/library-openrefine/pull/137. Closing this now.
