### ISSUE TITLE
Split "Basic OpenRefine functions I" into more granular lessons

### ISSUE THREAD

**Issue by ostephens** [data-lessons/library-openrefine#14]
Suggest the following:
1. Layout, organising columns, sorting data (all teaching)
2. Introduction to facets and filters
3. Introduction to rows and records
4. Introduction to clustering

**Comment by weaverbel** [comment]
+1 to that. Also some of the UCSD people were quite excited about the GREL abilities so a more advanced GREL bit would probably be appreciated, e.g. I used a GREL thing to turn two columns into one so I could have a single column for a name instead of forename in one and surname in another. (I copied to another column and then combined.) Really useful thing to show I think as well as showing how to split data up into separate columns. Just my two cents ...

**Comment by ostephens** [comment]
Exercise 10 (currently in basic functions II) could be changed to include the creation of new columns for family name and first name(s).

**Comment by ostephens** [comment]
I think the challenge with adding more GREL is time. I think there is probably over 3 hours worth of material here already so the question becomes what to take out to add more on writing GREL expressions?

**Comment by weaverbel** [comment]
@ostephens Good point. Let's go down the GREL road if we look at developing a really advanced OpenRefine class. Maybe some of the UCSD people might step up as they were keen. Fine to leave it for now.

**Comment by pitviper6** [comment]
Hey, a UCSD person here!  I'll work on developing a grel lesson - if we keep these bits fairly modular, we can plug and play depending on the sophistication of our audience.

**Comment by ccronje** [comment]
+1 to a GREL lesson. I think it would be a nice way to isolate/focus on the many functionalities of OR.

**Comment by weaverbel** [comment]
Another very enthusiastic +1 to some GREL @pitviper6 ! People in my last workshop were quite keen to learn more GREL. Joining columns, splitting columns would be good, replacing text/deleting text, etc

**Comment by pitviper6** [comment]
I'm starting to address this issue by breaking this into more granular lessons.  Just to be clear, we want four separate episodes, with titles like "Basic Open Refine Functions: Layout, Columns and Sorting"; "Basic Open Refine Functions: Facets and Filters" etc.?

**Comment by weaverbel** [comment]
@pitviper6 Sounds good. @ostephens any thoughts?

**Comment by ostephens** [comment]
@pitviper6 Yes - that was basically my view - basically I thought this would benefit from being shorter lessons - say 15-20 minutes at a time rather than 60 minutes all together.

Probably the biggest part of the work is adding appropriate questions/aims to each part of the lesson :)

**Comment by pitviper6** [comment]
Cool, I was on the right wavelength. I was thinking about structuring it as a demo with some library data I've got, and then use the current lesson data as exercises to which they can apply the stuff they learn in the demo to reinforce the concepts.

**Comment by ccronje** [comment]
Hi @ostephens @weaverbel @pitviper6, just going through each issue for mozsprint. Can you please let me know if this sounds ok?

1. Do we still want to split this into 4 ~20min episodes? If not, I'll close the issue
2. [new issue] Modify Exercise 10 to include the creation of new columns for family name and first name(s) using GREL transformation
3. [new issue] Create advanced GREL exercises (the current lesson is full but this could become part of an Advanced OpenRefine lesson which will need a new issue too...)
4. [new issue] Advanced OpenRefine lesson development

**Comment by ccronje** [comment]
Just adding @pitviper6's thoughts https://github.com/data-lessons/library-openrefine/pull/46#issuecomment-301247560 in reference to point 1 :-)

**Comment by ostephens** [comment]
@ccronje thanks for all your work around these issues 👍 

1. Yes I'm still in favour of breaking this into ~20min episodes
2. Sounds good
3. Think general feel is that 'cross' and 'replace' need adding to current lesson
4. Happy to see Advanced OR lesson

**Comment by ccronje** [comment]
No worries @ostephens, thanks for your help. I've created the new issues and added the mozsprint label to the other two 'split into more granular' issues.

**Comment by ostephens** [comment]
So how about this as a proposal for breaking this down a bit - have the following episodes

1. Layout of OR, Rows vs Records
2. Reordering/Renaming Cols; Sorting;
3. Filters, Facets and Clustering

This splits a 60 min episode into three which I think is about right, but I'm not completely sure these are equally balanced (so about 20 mins each) - although I think the structure is logical. Also means some reordering of current content and brings Rows/Records in earlier (which might be a bit complicated?)

Could potentially switch order of 2 & 3 to get to the interesting bit earlier in the lesson.

**Comment by ostephens** [comment]
See PR #72
