### ISSUE TITLE
Backup when refine not working

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-openrefine#153]
Sometimes Refine doesn't work on an attendees laptop: it is installed incorrectly, they've installed the wrong thing, it just unfathomably doesn't work.

Now, peer programming is great from a pedagogical point of view, so "work with someone else" is a good option. But prompted by @weaverbel, we should consider adding a backup to our Instructor Notes.

Is http://refinepro.com/ the best option here?

**Comment by ostephens** [comment]
RefinePro have been very supportive of workshops (not specifically LC) in the past and happy to offer free access for workshops - but this needs to be arranged in advance I think.

For adhoc cloud based OpenRefine, at the moment the Data Scientist Workbench looks good https://datascientistworkbench.com (which @weaverbel made me aware of and has used in a workshop I think). It's free to signup and offers access to a number of tools 'in the cloud' including OpenRefine

**Comment by weaverbel** [comment]
I like the data sci workbench but we must be sure to link to the right place if we do link it. The link @ostephens has listed won't get you to the right spot, I don't think. ThisHIS is the right one: https://my.datascientistworkbench.com/login - the MY in the URL is the crucial bit. And it works a treat and we were able to open the dataset no problems ...

**Comment by ccronje** [comment]
Thanks all, https://my.datascientistworkbench.com/ and http://refinepro.com/ are listed as workarounds in the Instructor Notes at http://data-lessons.github.io/library-openrefine/guide/.
