### ISSUE TITLE
forking to dh-openrefine repo

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-openrefine#27]
@weaverbel I think @tracykteal may need to do this as well please.

**Comment by weaverbel** [comment]
@ccronje @ostephens I couldn't fork it either, but I do have powers to create a new repo altogether here. Could we do it that way - I create a repo with the right name and then I could clone the existing one to my local machine, rename it to the new repo name, and then push to the new repo from the command line. Would that work? I think so.

**Comment by ccronje** [comment]
@weaverbel I wonder if this will make syncing/updating overlapping content complicated? But if the two repos have completely separate lives your solution sounds logical :-)

**Comment by weaverbel** [comment]
@ccronje One day I will get to this ... just completely swamped at the moment

**Comment by ccronje** [comment]
@weaverbel I'm able to create a new repo too so I tried. I ended up doing it in GHdesktop as I was having cryptic message troubles on the commandline. I cloned library-openrefine and dh-openrefine, copied the files over, then commited & synced dh-openrefine. However, the gh-pages branch from library-OR defaulted to master branch on dh-OR so the jekyll rendering is not working, and I didn't realise the commit msg would duplicate across every single file :-0 (if it's too much of a mess I'll just delete the repo & try again! I think I should have created a default Readme when creating the new repo so I could create a gh-pages branch).

**Comment by ccronje** [comment]
@weaverbel I deleted the new repo to avoid any confusion. The only activity had been my own.

**Comment by cmacdonell** [comment]
In a nutshell, forking is not the way to go about it.  The new repo is ready now https://data-lessons.github.io/dh-openrefine/

**Comment by ccronje** [comment]
Many thanks for your help @cmacdonell. Can you please outline the steps I should have taken to copy the repo over? For next time :-)
