### ISSUE TITLE
Typo in text

### ISSUE THREAD

**Issue by VictorE87** [data-lessons/library-openrefine#4]
In the Basic Open Refine functions I there is a typo in the last phrase of the paragraph about Filters

**Comment by ostephens** [comment]
@VictorE87 can you say what the typo is - I'm struggling to find it

**Comment by ccronje** [comment]
@ostephens the only thing I can spot is a missing full stop "You can also use regular expressions in the filter"

**Comment by ostephens** [comment]
Thanks @ccronje - PR now submitted
