### ISSUE TITLE
numbering of exercises

### ISSUE THREAD

**Issue by mkuzak** [data-lessons/library-openrefine#41]
Currently exercises are numbered across whole lesson. For example exercises 1 in episode 1 and then 2, 3, 4 in episode 2. I find it more intuitive and easier to maintain when the numbering is per episode. I was wondering what other people think about it.

**Comment by drjwbaker** [comment]
When teaching it in real life, having Exercise 1 in episode 2 and Exercise 2 in episode 3 makes more sense to me. But it you take them in chucks I can see how this might not be intuitive. Can we compromise on 1.1 (for ep1 ex1), 1.2 (for ep1 ex2), 3.1 (for ep3 ex1) et cetera?

**Comment by mkuzak** [comment]
+1 for 1.1 1.2 syntax

**Comment by drjwbaker** [comment]
If this is proposed to go across all the lessons we need to loop in all the lesson maintainers.

**Comment by mkuzak** [comment]
true, I can open an issue on data-lessons/librarycarpentry

**Comment by drjwbaker** [comment]
Okay. The other option is to leave it as it is, describe the process of downloading 'raw' data from the GitHub website, and see that as a learning outcome?

**Comment by mkuzak** [comment]
Your last comment refers to issue #42 ?

**Comment by drjwbaker** [comment]
Oops. Yes :)

**Comment by mkuzak** [comment]
I just looked at how it is done in SC lessons. And there is no numbering at all. Also the new templates allow for nicer rendering of exercises with hiding of the solutions. My suggestion is to just stick to how it's done in SC.

**Comment by drjwbaker** [comment]
Okay.

**Comment by ccronje** [comment]
Closing this now as @mkuzak will implement this (discussion at #43).
