### ISSUE TITLE
link to dataset

### ISSUE THREAD

**Issue by mkuzak** [data-lessons/library-openrefine#42]
There is no link which learners could use to download the dataset. Its actually hard to get the dataset now. You need to navigate on github to data directory, then view raw and then save as...
My questions are:
* Shall we put data on figshare and add links in the lessons?
* What is the origin how is it licensed?
* Do we have any description of the dataset to add on figshare page?

I'm happy to do the work, but wanted to get some feedback on it first.

**Comment by drjwbaker** [comment]
Which dataset are you referring to here?

**Comment by mkuzak** [comment]
I thought about
https://github.com/data-lessons/library-openrefine/blob/gh-pages/data/doaj-article-sample.csv
but that applies to all three datasets in `data` directory.

**Comment by drjwbaker** [comment]
Okay. The other option is to leave it as it is, describe the process of downloading 'raw' data from the GitHub website, and see that as a learning outcome?

**Comment by mkuzak** [comment]
I don't like it, because this lesson is about openrefine and not github and we loose focus that way. I think putting it on figshare and adding link is more elegant, but we need more info from people who contributed datasets. On the other hand it's not a big deal so I can leave with your solution too.

**Comment by drjwbaker** [comment]
Okay. Makes sense. Figshare just feels like too formal a venue. Do we really want to mint a DOI for a sample training dataset? What do DC/SWC do?

**Comment by ostephens** [comment]
I don't think Figshare is appropriate - especially as the data may have been deliberately doctored to an incorrect or less well formatted state in order for the lessons to work.

For the main data file used in the lesson, the link in setup.md goes directly to the raw file on github to avoid the issue with having to switch to the raw view of the file in github. This seems an OK approach to me.

**Comment by mkuzak** [comment]
@drjwbaker @ostephens I don't think we need a DIO. I suggested Figshare for convenience.  DC stores ecology dataset on [Figshare](https://figshare.com/articles/Portal_Project_Teaching_Database/1314459)

**Comment by ostephens** [comment]
I don't understand the logic of using Figshare for this. What is wrong with a link to the raw file on Github?

That said I'll go with a majority view

**Comment by mkuzak** [comment]
Git in general is not a good place to store data. This is not so much of a problem with small csv files, but:
- big files slow down git considerably
- `xlsx` files dont diff well

**Comment by ostephens** [comment]
We are only storing small files, and diff isn't a particular requirement I don't think?

**Comment by mkuzak** [comment]
Fair enough, lets keep it in github then.
One last question. When is more intuitive / easier to do:
- use [this url](https://github.com/data-lessons/library-openrefine/blob/gh-pages/data/UCSD_Guardian.csv) and click download button
- use [this url](https://raw.githubusercontent.com/data-lessons/library-openrefine/gh-pages/data/doaj-article-sample.csv) and do `File` -> `Save as...` in browser

I like the button solution more, but lets do what majority says.

**Comment by mkuzak** [comment]
I also recall two of the reasons to use Figshare for hosting datasets in DC case were:
- easier programatic download (form iPython or R console)
- multiple lessons using the same dataset

**Comment by ostephens** [comment]
Clicking the button redirects to the second URL - so I think the second approach is better because it saves a click and allows us to put explicit instructions on the screen next to the link (the behaviour of the download button is at the mercy of the browser)

**Comment by mkuzak** [comment]
You're right. Actually clicking the button has different results, depending on type of the file. It does work differently with `.xlsx` files.
Lets keep the current solution then and sorry for getting you into this whole rant.

**Comment by ostephens** [comment]
Those two reasons make sense to me but I don't think apply in this case (not yet at any rate).

**Comment by ostephens** [comment]
No problem. I note (now) that the library-sql lesson uses Figshare .... hmmm

**Comment by mkuzak** [comment]
:)

**Comment by mkuzak** [comment]
We can also take this discussion to gitter channel and see if people have strong opinions about it.

**Comment by ccronje** [comment]
We seem to be missing this 'Setup' menu item in our rendered lessons (for example see http://swcarpentry.github.io/shell-novice/setup/).

**Comment by mkuzak** [comment]
Yes, this is why I started this whole discussion :). I did miss the existence of setup.md file though.

**Comment by ostephens** [comment]
Any idea why the setup menu item isn't there? It contains essential info for this lesson

**Comment by pitviper6** [comment]
Just chiming in to say that the UCSDGuardian dataset wasn't edited, but I didn't originate the doaj lesson, so I don't know if that one has been doctored to include errors for cleanup.

**Comment by pitviper6** [comment]
@ostephens I have no idea why the setup isn't there, but it would be good to include it!  We could add that as a new issue.

**Comment by mkuzak** [comment]
I think we can close this issue and add the menu item related

**Comment by ostephens** [comment]
I made changes to the DOAJ dataset for the purposes of illustrating specific functionality in OR. None of these are factual changes, just structural

**Comment by ccronje** [comment]
The _Setup menu item_ is an issue across lessons so I've created an issue over here https://github.com/data-lessons/librarycarpentry/issues/9. Closing this one now.
