### ISSUE TITLE
Pulling in further examples

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-openrefine#48]
So, @scottythered (metdata & archive person) pointed me to his excellent Refine tutorial.

At https://github.com/scottythered/gratefuldata/wiki/Module-1E:-ASCAP-Data-(Further-Cleaning-and-Enriching)#enriching he demonstrates `cell.cross`. I must admit I wasn't aware of this functionality (and wish I was!) Are any of the datasets or examples that we have compatible with adding something about this in? If not, don't worry: perhaps we can just point to this in our further resources section.

**Comment by scottythered** [comment]
Would be happy to join up if you need any volunteers in the future!

**Comment by pitviper6** [comment]
This is great! I'll take a look and see if it would work with the UCSDGuardian data.

**Comment by ostephens** [comment]
The cross function is covered right at the end of the Advanced lesson but there isn't currently any practical exercise attached - this was due to time limitations in the original sessions. It's incredibly useful - I use it all the time. Recommend checking out the VIB BITS extension which makes it even easier to use

**Comment by ostephens** [comment]
Oh and @scottythered's tutorial is v cool

**Comment by drjwbaker** [comment]
Okay. I sensed that time was/remains a limiting factor in the functionality we can teach here. But if is can worked into the exercises in some way, that would be great. Thanks for the offer @scottythered. We always need fresh eyes. @pitviper6 & @ostephens coordinate this lesson, so I'll leave it to you three to discuss potential development areas.

**Comment by ccronje** [comment]
There was talk in Portland of swapping out data in lessons to make them 'flexible' but under the umbrella of information science - but I'm not sure how easy this would be seeing many exercises are dataset-specific.

Would you like me to:
1. Create a mozsprint issue to discuss how best to swap out data
2. Create a mozsprint issue for including an example for 'Using the ‘cross’ function to lookup data in other OpenRefine projects' in http://data-lessons.github.io/library-openrefine/05-advance-functions/
3. Close this issue

**Comment by ostephens** [comment]
@ccronje yes please!

Agree with your concerns about swapping out data - the only realistic way I can see of achieving this is separate lessons with separate data sets - I think the SWC templating system means it's difficult to achieve this in a sensible way with GitHub - but v open to suggestions for achieving this as there is obvious demand.

**Comment by weaverbel** [comment]
@ccronje @ostephens 

Voting for 1. Create a mozsprint issue to discuss how best to swap out data

**Comment by ccronje** [comment]
Closing this issue as the topics of discussion have been incorporated into new mozsprint issues.
