### ISSUE TITLE
Where to DL the doaj-article-sample.csv file

### ISSUE THREAD

**Issue by richyvk** [data-lessons/library-openrefine#49]
Hi.

Exercise 1 on the page http://data-lessons.github.io/library-openrefine/02-importing-data/ asks you to "locate the file called which you previously downloaded ‘doaj-article-sample.csv’". I can't find any reference on where you can DL this file from?

**Comment by cmacdonell** [comment]
Hi,

the file is the data directory in the repo: https://github.com/data-lessons/library-openrefine/blob/gh-pages/data/doaj-article-sample.csv

But it should be linked somewhere, I recall it was.  Thanks for catching that.

**Comment by ostephens** [comment]
The directions to download the file are in the 'setup' https://github.com/data-lessons/library-openrefine/blob/gh-pages/setup.md

**Comment by richyvk** [comment]
Aha. I didn't even notice the setup page! Perhaps a link to it at the point in lesson 2 where the file is mentioned might be good?

**Comment by ostephens** [comment]
Fixed by PR #52
