### ISSUE TITLE
Exercise 5 doesn't work that way

### ISSUE THREAD

**Issue by VictorE87** [data-lessons/library-openrefine#5]
I tried to do everything in Exercise 5 of Basic OpenRefine functions I, but switching from rows to records mode doesn't change anything in the numbering

**Comment by ostephens** [comment]
Can't recreate this problem. When I follow Exercise 5 it seems to work for me. See screenshot - no number in second row (Angelo Plastino in Author col) as expected:

<img width="548" alt="screen shot 2016-06-03 at 17 00 58" src="https://cloud.githubusercontent.com/assets/576174/15784971/da63250c-29ac-11e6-952c-a0adff89e284.png">

Can someone else test?

**Comment by ccronje** [comment]
@ostephens @VictorE87 This exercise works for me. 'Split multi-valued cells in column Authors' shows 4009 rows, then switching to records shows 1001 records. (I'm using OpenRefine version 2.6-rc.2)

**Comment by ccronje** [comment]
@ostephens Not sure if this is a bug/design but the number of rows = number of records if Authors is the first column. Might need to add a note about this incase they move around columns in earlier exercise. Also, if they accidentally select `Edit column > Split into several columns...` the numbers of rows and records are the same. Perhaps a caveat may help.

**Comment by ostephens** [comment]
That's OR design - ORs handling of 'records' is quite delicate as it depends on blank spaces to know that items belong to the same record. If you move the Author column to be the first column then after the split all the cells in the first column are populated (no blanks) and so OR assumes each is a separate record.

**Comment by ccronje** [comment]
Thanks @ostephens. I think this can be closed now.
