### ISSUE TITLE
Missing image files

### ISSUE THREAD

**Issue by richyvk** [data-lessons/library-openrefine#50]
Exercise 5 on lesson 3 page (http://data-lessons.github.io/library-openrefine/03-basic-functions-I/) links to two files, records.png and rows.png. These files are missing from assets/img folder so the links are broken :(

**Comment by mkuzak** [comment]
@cmacdonell that was a mistake, I was applying a new template and did not realise I'm deleting images used in the lesson.

**Comment by mkuzak** [comment]
Fixed in new pull request.
