### ISSUE TITLE
Support for Mercian Research Data Management Group (UK)

### ISSUE THREAD

**Issue by wjbfarrell** [data-lessons/library-openrefine#53]
Hello,

I have been talking to James Baker about Library Carpentry providing some infrastructural support for the [Mercian RDM Support Group ](https://merciancollaboration.org.uk/research-data-management-support-group).  We were particularly interested in running a workshop on Open Refine. I wonder if anyone would like to explore this further with us.

Thanks,

William Farrell,
University of Leicester Library

**Comment by ostephens** [comment]
Hi @wjbfarrell 

I'd be happy to explore this with you. I'm based in Leamington Spa (near Coventry) and wrote and delivered the original library carpentry OpenRefine lesson. Probably easiest if we move the discussion to email? (owen at ostephens.com)

**Comment by jezcope** [comment]
@wjbfarrell I may be able to help too. I can certainly give you some pointers on hosting a Library Carpentry course. We still need to agree internally how much of my time I can dedicate to LC but I might be able to do some instructing too.

PS. Say hi to Laurian, I think she was up here in Sheffield last week but I missed her.

**Comment by wjbfarrell** [comment]
Hi Jez, thanks. Let me know what your email is, and I'll include you in the message I was going to send to Owen. 

Laurian says hi.

**Comment by jezcope** [comment]
@wjbfarrell j dot s dot cope at sheffield dot ac dot uk (though I'm sure most spam bots are clever enough to see through simple transforms like that these days!)

**Comment by drjwbaker** [comment]
Thanks for picking this up @ostephens & @jezcope.
