### ISSUE TITLE
Exercise 8

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-openrefine#57]
Hi @ostephens, the publishers in this example don't appear to be in uppercase in the csv download.

**Comment by ostephens** [comment]
@ccronje it is the article Titles for articles published by those particular publishers that are in uppercase, not the publisher names.

Do you think wording of exercise could be improved to make this clearer?

**Comment by ccronje** [comment]
Sorry @ostephens, I don't know why I didn't see it. Wording is good thanks.
