### ISSUE TITLE
Typo in Basic OpenRefine Functions ||

### ISSUE THREAD

**Issue by VictorE87** [data-lessons/library-openrefine#6]
In the introduction there is a sentence which says that GREL expressions are (to some extend) similar to Excel Forumla, which has to be Excel Formula

**Comment by VictorE87** [comment]
The first sentence in the second paragraph after the heading Data Types is misspelled

**Comment by ostephens** [comment]
"Excel Forumla" typo fixed by 3d0b281

**Comment by ostephens** [comment]
Can't see the other typo. @VictorE87 can you clarify what is misspelled after the Data Types heading?

**Comment by ccronje** [comment]
@ostephens I think it's this one 

> Data types in OpenRefine Every piece of data in OpenRefine is has a 'type'.

**Comment by ostephens** [comment]
Thanks @ccronje PR now submitted

**Comment by ccronje** [comment]
Thanks @ostephens - is "Data types in OpenRefine" missing a triple hash? (looking at "Dates and Numbers" just below it)

**Comment by ostephens** [comment]
It is - I saw that earlier and thought it had been fixed but obviously not. I've added a fix to the PR
