### ISSUE TITLE
Improve lesson objectives

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-openrefine#66]
Improve the lesson/learning objectives in the Overview box at the top of each episode e.g. http://data-lessons.github.io/library-openrefine/03-basic-functions-I/, http://data-lessons.github.io/library-openrefine/04-basic-functions-II/.

Please see **Writing Learning Objectives** http://swcarpentry.github.io/instructor-training/19-lessons/.

**Comment by ostephens** [comment]
Ideally coordinate this with any work on #14 and #15 which propose breaking down the current episodes into smaller chunks - we can then have more specific lesson objectives for the smaller episodes

**Comment by ccronje** [comment]
Closing this high-level issue in favour of the episode-specific ones created by @ostephens.
