### ISSUE TITLE
Expression not well explained

### ISSUE THREAD

**Issue by VictorE87** [data-lessons/library-openrefine#7]
In Exercise 10 you have to use match to find the comma's in the names of the authors and then split it in an array. I think that match is not enough explained in the text. It is not in the text before the exercise and it is not clear enough what those asterisks or slashes mean. I think it could be better explained

**Comment by pitviper6** [comment]
Added a brief explanation of the expression, and created a PR.

**Comment by ccronje** [comment]
Thanks @pitviper6

**Comment by pitviper6** [comment]
You're welcome!  I hope my explanation makes sense, lol!
