### ISSUE TITLE
Exercise 1 might be clearer with a screen capture

### ISSUE THREAD

**Issue by jmjamison** [data-lessons/library-openrefine#74]
'Exercise 1: Create your first Open Refine project (using provided data)' might be clearer with a screen capture that has items mentioned in the exercise labeled.  (I'll get started with this one.)

---

**Comment by jt14den** [comment]
I think this is a good idea. When I teach the R lesson in SWC, there are two screen caps of R Studio in the opening episode. One for the loading data page in Open Refine could help.

**Comment by cmacdonell** [comment]
Yes, screencaps are really good when starting out with such a graphical tool as OR, similar to RStudio.

**Comment by scottcpeterson** [comment]
Going through OR with Kate, and she said a screen shot of the loading data page would be helpful.

**Comment by scottcpeterson** [comment]
Step 4 and 5 of loading the data in OR might be better explained by a screen shot and saying that "Ensure the first row is used to create the column headings by checking the box Parse next 1 line(s) as column headers," and the same with following step, "Make sure OpenRefine doesn’t try to automatically detect numbers and dates by making sure that parse cell text into numbers, dates... is unchecked.

**Comment by ostephens** [comment]
Fixed by #84
