### ISSUE TITLE
Exercise language does not match Refine

### ISSUE THREAD

**Issue by allisonbrown44** [data-lessons/library-openrefine#87]
In this case you need to:
3. Set the ‘Character encoding’ to UTF-8
4. Ensure the first row is used to create the column headings
5. Make sure OpenRefine doesn’t try to automatically detect numbers and dates

3 - 'Set the' does not make it clear that you have to click in the box
5 - Where do you check that Refine will not automatically detect numbers and dates? Is it related to 'Parse cell text into numbers, dates, ...'

**Comment by ostephens** [comment]
Wording now amended to fix this by #81 and #113
